spring:
  mail:
    host: smtp.gmail.com
    username: monemail@gmail.com #Your sender mail
    password: aaaabbbbccccdddd #Your Gmail 2FA credential
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
server:
  port: 9000

