spring:
  mail:
    host: smtp.gmail.com
    username: mirfou23@gmail.com
    password: ecrknszasaxftizx
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
server:
  port: 9000
#MES4B4YRCA724343PSQ971KY

